name: CI-smoke

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout
      - uses: actions/checkout@v4

      # 2 Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3 Install deps
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4 Download MNIST for evaluation
      - name: Download MNIST
        run: python scripts/download_mnist.py --root data/

      # 5 Run eval_test.py and assert accuracy ≥ 99 %
      - name: Evaluate test accuracy
        run: |
          python - << 'PY'
import re, subprocess, sys
# run the existing script
output = subprocess.check_output(["python", "scripts/eval_test.py"], text=True)
print(output)

match = re.search(r'([0-9]+\.[0-9]+)', output)   # first float in the line
acc = float(match.group(1)) if match else 0.0
print(f"Parsed accuracy = {acc:.2f}%")

if acc < 99.0:
    sys.exit(f"CI failed: accuracy {acc:.2f}% is below 99.0%")
PY
