name: CI-smoke
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Cache MNIST dataset
        uses: actions/cache@v4
        with:
          path: data/MNIST
          key: mnist-v1

      - name: Download MNIST
        run: python scripts/download_mnist.py --root data/

      - name: Evaluate test accuracy
        run: python ci_eval.py
