name: CI-smoke

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1 Check out code
    - uses: actions/checkout@v4

    # 2 Set up Python 3.10
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # 3 Install requirements
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4 Download MNIST once (cached in repo’s `data/`)
    - name: Fetch MNIST
      run: |
        python scripts/download_mnist.py --root data/

    # 5 Run evaluation and assert accuracy ≥ 99.0 %
    - name: Evaluate test accuracy
      run: |
        python scripts/eval_test.py > test_out.txt
        ACC=$(grep -oE '[0-9]+\\.[0-9]+' test_out.txt)
        echo "Test-set accuracy = $ACC %"
        python - << 'PY'
import sys, re, pathlib
acc = float(re.search(r'([0-9]+\\.[0-9]+)', pathlib.Path("test_out.txt").read_text()).group(1))
assert acc >= 99.0, f"Accuracy {acc:.2f}% is below 99.0%"
PY
